# Generated by Django 5.1.1 on 2024-10-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Hosting Main',
                'verbose_name_plural': 'Hosting Main',
            },
        ),
        migrations.CreateModel(
            name='HostingService1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description1', models.CharField(max_length=255)),
                ('description2', models.CharField(max_length=255)),
                ('description3', models.CharField(max_length=255)),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hosting Service1',
                'verbose_name_plural': 'Hosting Service1',
            },
        ),
        migrations.CreateModel(
            name='HostingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hosting Services',
                'verbose_name_plural': 'Hosting Services',
            },
        ),
        migrations.CreateModel(
            name='Trusted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trusted')),
            ],
            options={
                'verbose_name': 'Trusted',
                'verbose_name_plural': 'Trusted',
            },
        ),
        migrations.CreateModel(
            name='TrustedMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trusted_main')),
            ],
            options={
                'verbose_name': 'Trusted Main',
                'verbose_name_plural': 'Trusted Main',
            },
        ),
    ]
