# Generated by Django 5.1.1 on 2024-10-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cloudmain_cloudplans_featuresblocks_featuresmain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudplans',
            name='price',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='featuresblocks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='features_blocks'),
        ),
    ]
