# Generated by Django 5.1.1 on 2024-10-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_background_members_ourteam_ourwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='description',
        ),
        migrations.AddField(
            model_name='background',
            name='description1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='background',
            name='description2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
