# Generated by Django 5.1.1 on 2024-10-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_background_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='description1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='background',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='ourwork',
            name='description',
        ),
        migrations.AddField(
            model_name='ourwork',
            name='description1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourwork',
            name='description2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
