# Generated by Django 5.1.1 on 2024-10-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_description1_background_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourwork',
            name='title',
        ),
        migrations.AddField(
            model_name='ourwork',
            name='link_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourwork',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
