# Generated by Django 5.1.1 on 2024-10-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_ourwork_title_ourwork_link_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(blank=True, max_length=200, null=True)),
                ('link_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Work Tabs',
                'verbose_name_plural': 'Work Tabs',
            },
        ),
        migrations.RemoveField(
            model_name='ourwork',
            name='link_name',
        ),
        migrations.RemoveField(
            model_name='ourwork',
            name='link_url',
        ),
    ]
