# Generated by Django 5.1.1 on 2024-10-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ourwork_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phon_class', models.CharField(max_length=255)),
                ('phon', models.CharField(max_length=255)),
                ('support_class', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('envelope_class', models.CharField(max_length=255)),
                ('envelope', models.CharField(max_length=255)),
                ('glob_class', models.CharField(max_length=255)),
                ('glob', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='ContactMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=55, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Main',
                'verbose_name_plural': 'Contact Main',
            },
        ),
        migrations.CreateModel(
            name='ServicesBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Services Blocks',
                'verbose_name_plural': 'Services Blocks',
            },
        ),
        migrations.CreateModel(
            name='ServicesMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=55, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Services Main',
                'verbose_name_plural': 'Services Main',
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='body',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='body',
        ),
        migrations.RemoveField(
            model_name='services',
            name='body',
        ),
        migrations.AddField(
            model_name='about',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tag',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='tag',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='tag',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='tag',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
