# Generated by Django 5.1.1 on 2024-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_contactinfo_contactmain_servicesblocks_servicesmain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='envelope',
            new_name='class_name',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='envelope_class',
            new_name='html_class',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='glob',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='glob_class',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phon',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phon_class',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='support',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='support_class',
        ),
        migrations.AlterField(
            model_name='contact',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactmain',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicesmain',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
