# Generated by Django 5.1.1 on 2024-10-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_envelope_contactinfo_class_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmain',
            old_name='tag',
            new_name='description1',
        ),
        migrations.RemoveField(
            model_name='contactmain',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contactmain',
            name='title',
        ),
        migrations.AddField(
            model_name='contactmain',
            name='description2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmain',
            name='tag1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmain',
            name='tag2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmain',
            name='title1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmain',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
