# Generated by Django 5.1.1 on 2024-11-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_description1_contactmain_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingplans',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='moreinformation',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='usefullinks',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='worktabs',
            name='link_url',
        ),
    ]
